spring:
  application:
    name: library-microservice
  profiles:
    active: prod
  liquibase:
    change-log: classpath:src/main/resources/db/changelog/changelog.sql

server:
  port: 8080

google:
  books:
    api:
      key: AIzaSyDgCwXgqdppgstEUUgIqEONyGWx78KAJxI
